apiVersion: operators.coreos.com/v1alpha1 
kind: Subscription 
metadata: 
  name: elastic-operator 
  namespace: operators 
spec: 
  channel: stable 
  name: elastic-cloud-eck 
  source: operatorhubio-catalog 
  sourceNamespace: ibm-system