---
# Source: ibmcloud-block-storage-plugin/templates/ibmc-block-bronze-StorageClass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibmc-block-bronze
  labels:
    app: ibmcloud-block-storage-plugin
    chart: ibmcloud-block-storage-plugin-1.7.1
    release: RELEASE-NAME
    heritage: Helm
provisioner: ibm.io/ibmc-block
parameters:
  type: "Endurance"
  iopsPerGB: "2"
  sizeRange: "[20-12000]Gi"
  fsType: "ext4"
  billingType: "hourly"
  classVersion: "2"
reclaimPolicy: "Delete"
allowVolumeExpansion: true
---
# Source: ibmcloud-block-storage-plugin/templates/ibmc-block-custom-StorageClass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibmc-block-custom
  labels:
    app: ibmcloud-block-storage-plugin
    chart: ibmcloud-block-storage-plugin-1.7.1
    release: RELEASE-NAME
    heritage: Helm
provisioner: ibm.io/ibmc-block
parameters:
  type: "Performance"
  sizeIOPSRange: |-
    [20-39]Gi:[100-1000]
    [40-79]Gi:[100-2000]
    [80-99]Gi:[100-4000]
    [100-499]Gi:[100-6000]
    [500-999]Gi:[100-10000]
    [1000-1999]Gi:[100-20000]
    [2000-2999]Gi:[200-40000]
    [3000-3999]Gi:[200-48000]
    [4000-7999]Gi:[300-48000]
    [8000-9999]Gi:[500-48000]
    [10000-12000]Gi:[1000-48000]
  fsType: "ext4"
  billingType: "hourly"
  classVersion: "2"
reclaimPolicy: "Delete"
allowVolumeExpansion: true
---
# Source: ibmcloud-block-storage-plugin/templates/ibmc-block-gold-StorageClass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibmc-block-gold
  labels:
    app: ibmcloud-block-storage-plugin
    chart: ibmcloud-block-storage-plugin-1.7.1
    release: RELEASE-NAME
    heritage: Helm
provisioner: ibm.io/ibmc-block
parameters:
  type: "Endurance"
  iopsPerGB: "10"
  sizeRange: "[20-4000]Gi"
  fsType: "ext4"
  billingType: "hourly"
  classVersion: "2"
reclaimPolicy: "Delete"
allowVolumeExpansion: true
---
# Source: ibmcloud-block-storage-plugin/templates/ibmc-block-retain-bronze-StorageClass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibmc-block-retain-bronze
  labels:
    app: ibmcloud-block-storage-plugin
    chart: ibmcloud-block-storage-plugin-1.7.1
    release: RELEASE-NAME
    heritage: Helm
provisioner: ibm.io/ibmc-block
parameters:
  type: "Endurance"
  iopsPerGB: "2"
  sizeRange: "[20-12000]Gi"
  fsType: "ext4"
  billingType: "hourly"
  classVersion: "2"
reclaimPolicy: "Retain"
allowVolumeExpansion: true
---
# Source: ibmcloud-block-storage-plugin/templates/ibmc-block-retain-custom-StorageClass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibmc-block-retain-custom
  labels:
    app: ibmcloud-block-storage-plugin
    chart: ibmcloud-block-storage-plugin-1.7.1
    release: RELEASE-NAME
    heritage: Helm
provisioner: ibm.io/ibmc-block
parameters:
  type: "Performance"
  sizeIOPSRange: |-
    [20-39]Gi:[100-1000]
    [40-79]Gi:[100-2000]
    [80-99]Gi:[100-4000]
    [100-499]Gi:[100-6000]
    [500-999]Gi:[100-10000]
    [1000-1999]Gi:[100-20000]
    [2000-2999]Gi:[200-40000]
    [3000-3999]Gi:[200-48000]
    [4000-7999]Gi:[300-48000]
    [8000-9999]Gi:[500-48000]
    [10000-12000]Gi:[1000-48000]
  fsType: "ext4"
  billingType: "hourly"
  classVersion: "2"
reclaimPolicy: "Retain"
allowVolumeExpansion: true
---
# Source: ibmcloud-block-storage-plugin/templates/ibmc-block-retain-gold-StorageClass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibmc-block-retain-gold
  labels:
    app: ibmcloud-block-storage-plugin
    chart: ibmcloud-block-storage-plugin-1.7.1
    release: RELEASE-NAME
    heritage: Helm
provisioner: ibm.io/ibmc-block
parameters:
  type: "Endurance"
  iopsPerGB: "10"
  sizeRange: "[20-4000]Gi"
  fsType: "ext4"
  billingType: "hourly"
  classVersion: "2"
reclaimPolicy: "Retain"
allowVolumeExpansion: true
---
# Source: ibmcloud-block-storage-plugin/templates/ibmc-block-retain-silver-StorageClass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibmc-block-retain-silver
  labels:
    app: ibmcloud-block-storage-plugin
    chart: ibmcloud-block-storage-plugin-1.7.1
    release: RELEASE-NAME
    heritage: Helm
provisioner: ibm.io/ibmc-block
parameters:
  type: "Endurance"
  iopsPerGB : "4"
  sizeRange: "[20-12000]Gi"
  fsType: "ext4"
  billingType: "hourly"
  classVersion: "2"
reclaimPolicy: "Retain"
allowVolumeExpansion: true
---
# Source: ibmcloud-block-storage-plugin/templates/ibmc-block-silver-StorageClass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibmc-block-silver
  labels:
    app: ibmcloud-block-storage-plugin
    chart: ibmcloud-block-storage-plugin-1.7.1
    release: RELEASE-NAME
    heritage: Helm
provisioner: ibm.io/ibmc-block
parameters:
  type: "Endurance"
  iopsPerGB : "4"
  sizeRange: "[20-12000]Gi"
  fsType: "ext4"
  billingType: "hourly"
  classVersion: "2"
reclaimPolicy: "Delete"
allowVolumeExpansion: true
---
# Source: ibmcloud-block-storage-plugin/templates/ibmcloud-block-storage-plugin-SA.yaml
# ServiceAccount for ibmcloud-block-storage-plugin
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibmcloud-block-storage-plugin
  namespace: kube-system
  labels:
    app: ibmcloud-block-storage-plugin
    chart: ibmcloud-block-storage-plugin-1.7.1
    release: RELEASE-NAME
    heritage: Helm
---
# Source: ibmcloud-block-storage-plugin/templates/ibmcloud-block-storage-plugin-BYOK-CR.yaml
#ClusterRole with minimum permissions required for ibmcloud-block-storage
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibmcloud-block-storage-plugin-byok
  labels:
    app: ibmcloud-block-storage-plugin
    chart: ibmcloud-block-storage-plugin-1.7.1
    release: RELEASE-NAME
    heritage: Helm
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create"]
---
# Source: ibmcloud-block-storage-plugin/templates/ibmcloud-block-storage-plugin-CR.yaml
#ClusterRole with minimum permissions required for ibmcloud-block-storage
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibmcloud-block-storage-plugin
  labels:
    app: ibmcloud-block-storage-plugin
    chart: ibmcloud-block-storage-plugin-1.7.1
    release: RELEASE-NAME
    heritage: Helm
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "watch", "create", "update", "patch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: []
  nonResourceURLs: ["/version"]
  verbs: ["get"]
---
# Source: ibmcloud-block-storage-plugin/templates/ibmcloud-block-storage-plugin-CRB.yaml
#ClusterRoleBinding for binding ClusterRole "ibmcloud-block-storage-plugin"
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibmcloud-block-storage-plugin
  labels:
    app: ibmcloud-block-storage-plugin
    chart: ibmcloud-block-storage-plugin-1.7.1
    release: RELEASE-NAME
    heritage: Helm
subjects:
- kind: ServiceAccount
  name: ibmcloud-block-storage-plugin
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: ibmcloud-block-storage-plugin
  apiGroup: rbac.authorization.k8s.io
---
# Source: ibmcloud-block-storage-plugin/templates/ibmcloud-block-storage-driver-DS.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ibmcloud-block-storage-driver
  namespace: kube-system
  labels:
    app: ibmcloud-block-storage-driver
    chart: ibmcloud-block-storage-plugin-1.7.1
    release: RELEASE-NAME
    heritage: Helm
spec:
  selector:
    matchLabels:
      app: ibmcloud-block-storage-driver
      release: RELEASE-NAME
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ibmcloud-block-storage-driver
        chart: ibmcloud-block-storage-plugin-1.7.1
        release: RELEASE-NAME
        heritage: Helm
      annotations:
        productID: ibmcloud-block-storage-plugin-1.7.1
        productName: ibmcloud-block-storage-plugin
        productVersion: 1.7.1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - {key: "ibm-cloud.kubernetes.io/iaas-provider", operator: In, values: [softlayer]}
              - {key: "kubernetes.io/arch", operator: In, values: [amd64]}
      containers:
        - name: ibmcloud-block-storage-driver-container
          image: "icr.io/ibm/ibmcloud-block-storage-driver:1.17"
          imagePullPolicy: Always
          env:
            - name: IBMC_FEATURE_GATES
              value: "KeyManagementBYOK=true"
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
             - mountPath: /host/usr
               name: host-usr
             - mountPath: /run/systemd
               name: sysd-run
             - mountPath: /host/etc
               name: host-etc
             - mountPath: /host/lib
               name: host-lib
             - mountPath: /host/var/log
               name: host-var-log
          livenessProbe:
            exec:
              command:
              - ls
              - /host/usr/libexec/kubernetes/kubelet-plugins/volume/exec/ibm~ibmc-block/ibmc-block
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "50Mi"
              cpu: "25m"
            limits:
              memory: "200Mi"
              cpu: "100m"
      hostNetwork: true
      serviceAccountName: ibmcloud-block-storage-plugin
      tolerations:
      - operator: "Exists"
      volumes:
        - name: host-usr
          hostPath:
             path: /usr/
        - name: sysd-run
          hostPath:
             path: /run/systemd
        - name: host-etc
          hostPath:
             path: /etc/
        - name: host-lib
          hostPath:
             path: /lib/
        - name: host-var-log
          hostPath:
             path: /var/log
---
# Source: ibmcloud-block-storage-plugin/templates/ibmcloud-block-storage-plugin-Deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibmcloud-block-storage-plugin
  namespace: kube-system
  labels:
    app: ibmcloud-block-storage-plugin
    chart: ibmcloud-block-storage-plugin-1.7.1
    release: RELEASE-NAME
    heritage: Helm
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: ibmcloud-block-storage-plugin
      release: RELEASE-NAME
  template:
    metadata:
      labels:
        app: ibmcloud-block-storage-plugin
        chart: ibmcloud-block-storage-plugin-1.7.1
        release: RELEASE-NAME
        heritage: Helm
      annotations:
        productID: ibmcloud-block-storage-plugin-1.7.1
        productName: ibmcloud-block-storage-plugin
        productVersion: 1.7.1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - {key: "ibm-cloud.kubernetes.io/iaas-provider", operator: In, values: [softlayer]}
              - {key: "kubernetes.io/arch", operator: In, values: [amd64]}
      containers:
        - name: ibmcloud-block-storage-plugin-container
          image: "icr.io/ibm/ibmcloud-block-storage-plugin:1.17"
          imagePullPolicy: Always
          args:
            - "--provisioner=ibm.io/ibmc-block"
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: PLUGIN_IMAGE
            value: "icr.io/ibm/ibmcloud-block-storage-plugin:1.17"
          - name: DEBUG_TRACE
            value: 'false'
          - name: STORAGE_CONFIG_PATH
            value: /etc/storage_ibmc
          - name: IBMC_FEATURE_GATES
            value: "KeyManagementBYOK=true"
          volumeMounts:
            - name: customer-auth
              mountPath: /etc/storage_ibmc
          livenessProbe:
            exec:
              command:
              - ls
              - /etc/storage_ibmc
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "300Mi"
              cpu: "300m"
          imagePullPolicy: Always
      serviceAccountName: ibmcloud-block-storage-plugin
      volumes:
        - name: customer-auth
          secret:
            secretName: storage-secret-store
---
# Source: ibmcloud-block-storage-plugin/templates/tests/ibmcloud-block-storage-plugin-test.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "ibmcloud-block-storage-plugin-test"
  labels:
    app: ibmcloud-block-storage-plugin
    chart: ibmcloud-block-storage-plugin-1.7.1
    release: RELEASE-NAME
    heritage: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - {key: "ibm-cloud.kubernetes.io/iaas-provider", operator: In, values: [softlayer]}
          - {key: "beta.kubernetes.io/arch", operator: In, values: [amd64]} 
        - matchExpressions:
          - {key: "ibm-cloud.kubernetes.io/iaas-provider", operator: In, values: [softlayer]}
          - {key: "kubernetes.io/arch", operator: In, values: [amd64]}
  containers:
  - name: ibmcloud-block-storage-plugin-test
    image: "icr.io/ibm/ibmcloud-block-storage-driver:1.17"
    imagePullPolicy: Always
    command: ["sh", "-c", 'expected_version=$(/home/armada-storage/ibmc-block version);
      installed_version=$(/host/usr/libexec/kubernetes/kubelet-plugins/volume/exec/ibm~ibmc-block/ibmc-block version);
      echo "expected_version: $expected_version";
      echo "installed_version: $installed_version";
      if [[ "$expected_version" == "$installed_version" ]]; then exit 0; else exit 1; fi']
    volumeMounts:
      - mountPath: /host/usr
        name: host-usr
  restartPolicy: Never
  volumes:
    - name: host-usr
      hostPath:
        path: /usr/
