apiVersion: charts.helm.k8s.io/v1alpha1
kind: Kong
metadata:
  name: load-balancer-kong
  namespace: kong
spec:
  proxy:
    type: LoadBalancer
  env:
    prefix: /kong_prefix/
  resources:
    limits:
      cpu: 500m
      memory: 2G
    requests:
      cpu: 100m
      memory: 512Mi
  ingressController:
    enabled: true
    ingressClass: kong-ingress-class
    installCRDs: false