apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-producer
  name: hello-world-producer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-producer
  template:
    metadata:
      labels:
        app: hello-world-producer
    spec:
      containers:
      - name: hello-world-producer
        image: strimzi/hello-world-producer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: kafka-cluster-kafka-bootstrap:9093
          - name: TOPIC
            value: my-topic-replicated
          - name: DELAY_MS
            value: "1000"
          - name: LOG_LEVEL
            value: "INFO"
          - name: MESSAGE_COUNT
            value: "1000000"
          - name: PRODUCER_ACKS
            value: "all"
          - name: CA_CRT
            valueFrom:
              secretKeyRef: 
                name: kafka-cluster-cluster-ca-cert
                key: ca.crt
          - name: USER_CRT
            valueFrom:
              secretKeyRef: 
                name: my-user
                key: user.crt            
          - name: USER_KEY
            valueFrom:
              secretKeyRef: 
                name: my-user
                key: user.key            
          - name: ADDITIONAL_CONFIG
            value: |
              retries=100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-consumer
  name: hello-world-consumer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-consumer
  template:
    metadata:
      labels:
        app: hello-world-consumer
    spec:
      containers:
      - name: hello-world-consumer
        image: strimzi/hello-world-consumer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: kafka-cluster-kafka-bootstrap:9093
          - name: TOPIC
            value: my-topic-replicated
          - name: CA_CRT
            valueFrom:
              secretKeyRef: 
                name: kafka-cluster-cluster-ca-cert
                key: ca.crt
          - name: USER_CRT
            valueFrom:
              secretKeyRef: 
                name: my-user
                key: user.crt            
          - name: USER_KEY
            valueFrom:
              secretKeyRef: 
                name: my-user
                key: user.key
          - name: GROUP_ID
            value: my-group
          - name: LOG_LEVEL
            value: "INFO"
          - name: MESSAGE_COUNT
            value: "1000000"
          - name: PRODUCER_ACKS
            value: "all"
          - name: ADDITIONAL_CONFIG
            value: |
              max.poll.records=100