apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: strimzi-kafka-operator
  namespace: operators
spec:
  channel: strimzi-0.19.x
  name: strimzi-kafka-operator
  source: operatorhubio-catalog
  sourceNamespace: ibm-system